// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Program_for_value;

namespace Program_for_value.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240605110513_textBox1.Text")]
    partial class textBox1Text
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10");

            modelBuilder.Entity("Program_for_value.Query", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ValueFrom")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueTo")
                        .HasColumnType("TEXT");

                    b.Property<float>("ValueToConvert")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Queries");
                });

            modelBuilder.Entity("Program_for_value.QueryResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<float>("Itogo")
                        .HasColumnType("REAL");

                    b.Property<int>("QueryId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Value1")
                        .HasColumnType("REAL");

                    b.Property<float>("Value2")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("QueryId");

                    b.ToTable("QueryResults");
                });

            modelBuilder.Entity("Program_for_value.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Program_for_value.Query", b =>
                {
                    b.HasOne("Program_for_value.User", "User")
                        .WithMany("Queries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Program_for_value.QueryResult", b =>
                {
                    b.HasOne("Program_for_value.Query", "Query")
                        .WithMany("QueryResults")
                        .HasForeignKey("QueryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
