// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WindowsFormsApp1;

namespace WindowsFormsApp1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10");

            modelBuilder.Entity("WindowsFormsApp1.Query", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ValueFrom")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueTo")
                        .HasColumnType("TEXT");

                    b.Property<float>("ValueToConvert")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Queries");
                });

            modelBuilder.Entity("WindowsFormsApp1.QueryResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<float>("Itogo")
                        .HasColumnType("REAL");

                    b.Property<int>("QueryId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Value1")
                        .HasColumnType("REAL");

                    b.Property<float>("Value2")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("QueryId");

                    b.ToTable("QueryResults");
                });

            modelBuilder.Entity("WindowsFormsApp1.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WindowsFormsApp1.Query", b =>
                {
                    b.HasOne("WindowsFormsApp1.User", "User")
                        .WithMany("Queries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WindowsFormsApp1.QueryResult", b =>
                {
                    b.HasOne("WindowsFormsApp1.Query", "Query")
                        .WithMany("QueryResults")
                        .HasForeignKey("QueryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
